# Generated by Django 2.2.12 on 2020-04-15 20:27

from django.db import IntegrityError, migrations, models, transaction
import phonenumber_field.modelfields


def set_phone_number_nulls(apps, schema_editor):
    User = apps.get_model('users', 'User')
    users = User.objects.all()
    for u in users:
        # Explicitly check if phone_number is '' and set it to None.
        if u.phone_number is not None and u.phone_number.strip() == '':
            try:
                with transaction.atomic():
                    u.phone_number = None
                    u.save()
            except IntegrityError:
                raise


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_fields_alter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.RunPython(set_phone_number_nulls),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text='Phone number used for 2FA Authentication.',
                max_length=128,
                null=True,
                region=None,
                unique=True
            ),
        ),
    ]
