# Generated by Django 2.2.12 on 2020-04-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authy_id',
            field=models.CharField(blank=True, help_text='Authentication ID from Twilio 2FA API.', max_length=12, null=True),
        ),
    ]
